### PR TITLE
add chinese readme for amoveo

### PR DESCRIPTION
**Pull request by kaidiren**

### CODE REVIEW

**Comment by zack-bitcoin** [comment]
Thank you for translating part of that page, it looks great.
If you get a chance, I hope you will translate the rest of that page.
https://github.com/zack-bitcoin/amoveo/blob/master/docs/cn/README.md

**Comment by kaidiren** [comment]
why not the same as https://github.com/zack-bitcoin/amoveo/blob/master/README.md ? why you write another readme looks different from the origin readme?

**Comment by zack-bitcoin** [comment]
This is a temporary solution until other things are translated.

**Comment by kaidiren** [comment]
ok

**Pull request merged**
