### PR TITLE
add api to get the average hashrate and block period. call block:mine…

### PR DESCRIPTION
**Pull request by cynic89**
I have attempted to calculate the hashrate over a sample of N blocks. The formula I use is hashrate = Difficuly/delta_time. Let me know what you think

### CODE REVIEW

**Comment by zack-bitcoin** [comment]
You are good at erlang, this is well written code.
You understand recursion and pattern matching well.
Thanks for your interest in Amoveo.

Finding the difference of all those block gaps, and then adding them together, that is the same thing as taking the different of the two blocks on the end and never looking up the blocks in the middle.
We store the blocks on the hard drive, so it is expensive to look them up.

Difficulty is stored in a scientific notation type format, it is not a value that can be added or divided by other values in the normal way. You cannot divide to find the hashrate like that.
I realize now that asking you to estimate the hashrate was no fair. I started working on it, and I have to look up a lot of library files.

Thank you for this first submission, I hope you will submit more code in the future.

**Comment by cynic89** [comment]
Yeah sorry I'm a bit new to blockchain code.... Will keep reading more so that I can be more useful in the future. Thanks for your patience, though.

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/blob/master/apps/amoveo_core/src/consensus/chain/block.erl#L542
Here is how I ended up doing it, if you are curious.
Reading your code first gave me ideas.

**Comment by cynic89** [comment]
Yeah saw the code. I was naive in my calculations. I just finished your dump and trie modules. Reading through amoveo_core which will take some time I guess. Meanwhile I thought we could port amoveo_http to elixir. Not that erlang is bad but elixir will the easier for new devs. What do you think?

**Pull request closed without merging**
